title: Cool Project
name: cool-project
author:
  name: Aaron Sky
  email: aaronsky@skyaaron.com
  github: aaronsky
description: A repo to stand the test of time
language: C#
banner: http://something.com/
tags:
  - Math
  - Data Structures
extra_resources:
  - King Piccolo
connections:
  - another-cool-project
  - a-less-cool-project