series: Intro to ATLAS
title: Cool Project
author:
  name: Aaron Sky
  email: aaronsky@skyaaron.com
  github: aaronsky
description: A repo to stand the test of time
language: C#
tags:
  - Math
  - Data Structures
extra_resources:
  - title: King Piccolo
    link: http://dragonball.wikia.com/wiki/King_Piccolo
connections:
  - series: Intro to ATLAS
    title: another-cool-project
  - series: Intro to ATLAS
    title: a-less-cool-project